version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
    networks:
      - arcaptcha-network
    restart: unless-stopped
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432" # "host or windows port: container port"

  admin:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    environment:
      SECRET: your_secret
      DATABASE_NAME: postgres
      DATABASE_PASSWORD: 123456
      DATABASE_HOST: postgres
      PORT: 5432
      DATABASE_USER: admin
    ports:
      - "3000:3000"
    networks:
      - arcaptcha-network
    depends_on:
      - postgres


networks:
  arcaptcha-network:

volumes:
  postgres:

