version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
    networks:
      - arcaptcha-network
    restart: unless-stopped
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432" # "host or windows port: container port"


networks:
  arcaptcha-network:

volumes:
  postgres:

