version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
    networks:
      - arcaptcha-network
    restart: unless-stopped
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432" # "host or windows port: container port"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./:/var/lib/pgadmin
      - ./:/var/lib/pgadmin/storage/pgadmin4_pgadmin.org
      # - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - arcaptcha-network
    restart: unless-stopped
    depends_on:
      - postgres
  admin:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    environment:
      SECRET: your_secret
      DATABASE_NAME: postgres
      DATABASE_PASSWORD: 123456
      DATABASE_HOST: postgres
      PORT: 5432
      DATABASE_USER: admin
    ports:
      - "3000:3000"
    networks:
      - arcaptcha-network
    depends_on:
      - postgres


networks:
  arcaptcha-network:

volumes:
  postgres:
  pgadmin:
